# Copyright skoved
# SPDX-License-Identifier: GPL-3.0-or-later
---
name: Testing
run-name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}
permissions:
  contents: read
  pull-requests: read
jobs:
  gotest:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Display Go Version
        run: go version
      - name: Test Go Code
        run: go test -v ./...
  goreleaser-test:
    name: Goreleaser Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --snapshot --clean
